version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5000
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    environment:
      - VITE_API_URL=http://backend:5000/api
    depends_on:
      - backend
    restart: unless-stopped
networks:
  default:
    driver: bridge 